### ISSUE TITLE
Not working with Nvim-tree. Opening it as a empty buffer,

### ISSUE THREAD

**Issue by reactVishnu** [pysan3/autosession.nvim#1]
![image](https://github.com/pysan3/autosession.nvim/assets/134265914/834cad58-8cd7-4ffd-b742-0cfeb6083d02)
D
![image](https://github.com/pysan3/autosession.nvim/assets/134265914/32993caf-e15f-4463-be98-a7c5f0d0640c)

Thanks for the plugin btw

**Comment by pysan3** [comment]
Hi thanks for using it! Happy to see someone actually using it in the wild lol.

Does this solution work for this plugin as well?

https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#workaround-when-using-rmagattiauto-session

**Comment by reactVishnu** [comment]
Thanks, the solution you gave worked for me.. 
Again thanks for the plugin
